name: flutter_yookassa_sdk
description: Yookassa SDK plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for making payments through Yookassa.
version: 0.2.0
homepage: https://github.com/wwwhttpru/flutter_yookassa_sdk
repository: https://github.com/wwwhttpru/flutter_yookassa_sdk
issue_tracker: https://github.com/wwwhttpru/flutter_yookassa_sdk/issues

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: yookassa_sdk_android

dependencies:
  flutter:
    sdk: flutter

  # For development. Remove/comment before publishing to pub.
dependency_overrides:
  yookassa_sdk_platform_interface:
    path: ../yookassa_sdk_platform_interface
  yookassa_sdk_android:
    path: ../yookassa_sdk_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  plugin_platform_interface: ^2.1.2